<style type="text/css">
    .vlablack_overlay {
        position: fixed;
        top: 0%;
        left: 0%;
        width: 100%;
        height: 100%;
        background-color: black;
        z-index: 1001;
        -moz-opacity: 0.5;
        opacity: .50;
        filter: alpha(opacity=55);
        display: none;
    }
    .vlawhite_content {
        position: fixed;
        top: 20%;
        left: 50%;
        background-color: #000;
        width: 600px;
        margin-left: -300px;
        height: auto;
        z-index: 1002;
        overflow: auto;
        color: #e8e5e5;
        display: none;
    }
    .vlawhite_content .vla-whose-form{
        margin:10px;
        border: 1px #e8e5e5 solid;
        text-align: center;
        padding: 50px 0 120px 0;
    }
    .vlawhite_content .vla-whose-form .btn-col-ban{
        width: 50%;
        float: left;
    }
    .vlawhite_content .vla-whose-form h2{
        font-weight: 700;
        margin: 0;
    }
    .vlawhite_content .vla-whose-form h3{
        margin: 1rem 0 4rem 0;
    }
    .vlawhite_content .vla-whose-form h4{
        font-weight: 300;
        margin: 0;
        line-height: 3rem;
    }
    .vlawhite_content .btn-col-ban button {
        background-color: #07a0ec;
        width: 130px;
        color: inherit;
        border: 1px solid #07a0ec;
    }
    .vlawhite_content .btn-col-ban .btn-no-age{
        background-color: inherit;
        border-color: #f6f6f6;
        color: #fff;
    }
    @media screen and (max-width: 599px){
        .vlawhite_content{
            width: 100%;
            left: 0;
            margin-left: 0;
        }
    }
	/* 隐藏 product detail中的 more infomation 选项卡 */
	.product.info.detailed #tab-label-additional {
		display:none;
	}
    strong.product.name.product-item-name {
        padding: 0 0 10px 3px;
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;
    }
    /*修改产品详情页的按钮宽度*/
    @media screen and (min-width: 768px){
        .page-layout-1column .product-item-info{
            width: 100%;
        }
        .page-layout-1column .product-item .price-box{
            margin: 15px 0 0;
        }
    }
    .page-layout-1column .products-grid .product-item {
        margin-left:0 !important;
    }
    .page-layout-1column .price-container .price, .page-layout-1column .product-inquire-btn {
        font-size: 1.6rem;
        padding-left: 3px;
    }
    .page-layout-1column .products.wrapper.grid.products-grid {
        margin: 0;
    }
    @media screen and (min-width: 1024px){
        .page-layout-1column .products-grid .product-item{
            width: 19%;
            margin-right: 1%;
        }
    }
</style>

<div class="vlawhite_content">
    <div class="vla-whose-form">
        <h1><img src="<?php echo $block->getViewFileUrl('images/vladdins_03.png'); ?> " alt="vladdin webpage prompt box" class="leftImage floatLeft"></h1>
        <h2>AGE VERIFICATION</h2>
        <h3>ARE YOU OF LEGAL SMOKING AGE?</h3>
        <div class="btn-col-ban">
            <button id="btn-yes-age">YES</button><h4>I am of legal smoking age</h4>
        </div>
        <div class="btn-col-ban">
            <a href="/"><button class="btn-no-age">NO</button></a><h4>I am NOT of legal smoking age</h4>
        </div>
    </div>
    <a class="vla-close-button"></a>
</div>
<div class="vlablack_overlay"></div>
<script type="text/javascript">
    require(['jquery'], function ($) {
		function _setCookie(c_name,value,expiredays)
		{
			var exdate=new Date()
			exdate.setDate(exdate.getDate()+expiredays)
			document.cookie=c_name+ "=" +escape(value)+
				((expiredays==null) ? "" : ";expires="+exdate.toGMTString())
		}
	
		function _getCookie(c_name)
		{
			if (document.cookie.length>0)
			{
				c_start=document.cookie.indexOf(c_name + "=")
				if (c_start!=-1)
				{
					c_start=c_start + c_name.length+1
					c_end=document.cookie.indexOf(";",c_start)
					if (c_end==-1) c_end=document.cookie.length
					return unescape(document.cookie.substring(c_start,c_end))
				}
			}
			return ""
		}
		
		
		$(document).ready(function(){
			if(!_getCookie('VLA_AGE_VERIFICATION')) {
				$(".vlablack_overlay, .vlawhite_content").css('display', 'block');
				
				window.VLA_AGE_VERIFICATION_timer = setInterval((function($) { return function() {
					if(_getCookie('VLA_AGE_VERIFICATION')) {
						clearInterval(window.VLA_AGE_VERIFICATION_timer);
						$(".vlablack_overlay, .vlawhite_content").css('display', 'none');
					}
				} })($), 2000);
            }
			
			$("#btn-yes-age").click(function() {
				_setCookie('VLA_AGE_VERIFICATION', 1, 30);
				$(".vlablack_overlay, .vlawhite_content").css('display', 'none');
			});
		});
	})
</script>

<?php
	$obMgr = \Magento\Framework\App\ObjectManager::getInstance();
	$register = $obMgr->get('\Magento\Framework\Registry');
	$product = $register->registry('product');
?>


<?php if($product): ?>
	<script>
		require(['jquery'], function ($) {
			var $ul = $('.breadcrumbs .items');
			var home = $ul.children()[0];
			var $li = $(home.outerHTML);
			$li.find('a').html('Products').attr('title', 'Products').attr('href', '/products');
			$(home).after($li);
		});
	</script>
<?php endif; ?>
