<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$assetRepository = $objectManager->get('Magento\Framework\View\Asset\Repository');
?>

<link href="<?php echo $assetRepository->createAsset('css/common.css')->getUrl(); ?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $assetRepository->createAsset('css/index.css')->getUrl(); ?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $assetRepository->createAsset('css/header.css')->getUrl(); ?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $assetRepository->createAsset('css/mobile.css')->getUrl(); ?>" rel="stylesheet" type="text/css"/>


<style>
	.columns .column.main{
		padding-bottom: 0;
	}
	#maincontent {
		padding: 0;
		margin: 0 !important;
		max-width: 100%;
		width: 100%;
	}

	.page-footer{
		margin-top: 0;
	}

	.product-re-page .introduce-title{
		position: relative;
	}

	.columns .column.main p{
		margin-bottom: 0;
	}

	.introduce-title h2{
		margin-top: 50px;
		margin-bottom: 80px;
	}

	.product-re-page{
		overflow: hidden;
	}

	.product-re-page .pro-banner{
		background: url('/media/wysiwyg/product/re_banner_bg.jpg') no-repeat center;
		background-size: cover;
		position: relative;
		height: auto;
	}

	.pro-banner-box {
		width: 100%;
		padding-top: 200px;
		padding-bottom: 100px;
	}

	li.pro-banner-l {
		margin-top: 7%;
	}

	.pro-banner-box li{
		width:50%;
		float: left;
	}

	.banner-logo {
		border-bottom: 2px solid rgba(255,255,255,0.42);
		padding-bottom: 30px;
	}

	.pro-banner-l .banner-text {
		font-size: 24px;
		color: #f6f6f6;
		margin-top: 20px;
		line-height: 1.5;
	}

	.buy-col{
		position: relative;
	}

	.buy-col a {
		position: absolute;
		top: 39%;
		left: 22.23%;
		width: 238px;
		height: 68px;
		background-color: #000000;
		box-shadow: 0px 2px 2px 0px rgba(0, 0, 0, 0.2), inset 0px 1px 0px 0px rgba(255, 255, 255, 0.44);
		border-radius: 5px;
		font-size: 38px;
		line-height: 68px;
		text-align: center;
		letter-spacing: 2px;
		color: #ffffff;
	}

	.flavors-content{
		position: relative;
		margin-top: 0;
	}

	.flavors-col .introduce-word{
		margin-top: 0;
		position: absolute;
		right: 0;
		top: 0;
		width: 29%;
	}

	.flavors-col .introduce-word ul li{
		width: 100%;
		margin-bottom: 80px;
		height: auto;
	}

	.introduce-img{
		height: auto;
		padding: 10px 0 20px;
	}

	.flavors-content  img{
		transform: rotate(0deg) translateX(-15%);
	}

	.flavors-content .introduce-img img{
		transform: none;
	}

	.design-col .introduce-title{
		position: absolute;
		width: 100%;
	}

	@media screen and (max-width: 1135px) {
		.flavors-content .introduce-img img{
			width: 70px;
		}

		.introduce-word ul li p{
			font-size: 14px;
		}

		.introduce-title h2{
			font-size: 30px;
		}

	}

	@media screen and (max-width: 1023px) {
		.buy-col a{
			font-size: 16px;
			width: 120px;
			height: 40px;
			line-height: 40px;
		}
	}


	@media screen and (max-width: 950px) {
		.flavors-col .introduce-word ul li{
			margin-bottom: 30px;
		}

		.introduce-title h2 {
			margin-top: 30px;
			margin-bottom: 40px;
		}

		.flavors-col .introduce-word ul li{
			padding: 10px 0 10px;
		}
	}

	@media screen and (max-width: 767px){
		.flavors-col .introduce-word{
			position: static;
			width: 100%;
		}

		.flavors-content img{
			transform: none;
		}

		.flavors-col .introduce-word ul li{
			width: 33.33%;
			margin-bottom: 0;
		}

		.introduce-img{
			padding: 0;
		}

		.pro-banner-l .banner-text{
			font-size: 14px;
		}

		.pro-banner-box{
			padding-top: 150px;
			padding-left: 10px;
			padding-right: 10px;
			box-sizing: border-box;
		}

		.introduce-title h2 {
			margin-top: 0px;
			margin-bottom: 40px;
			font-size: 20px;
		}

		.buy-col a{
			left: 10%;
			font-size: 14px;
			line-height: 30px;
			height: 30px;
			width: 100px;
			letter-spacing: 0;
		}

		.pro-banner-box{
			padding-bottom: 30px;
		}
	}

	@media screen and (max-width: 374px) {

	}




</style>

<?php echo $this->getLayout()
    ->createBlock('Magento\Framework\View\Element\Template')
    ->setTemplate('Own_Base::vladdin-header.phtml')
    ->toHtml(); ?>

<div class="product-re-page">
	<div class="pro-banner">
		<ul class="pro-banner-box w-1200 clearfix">
			<li class="pro-banner-l">
				<div class="banner-logo">
					<img src="/media/wysiwyg/product/re_logo.png" alt="The vladdin logo on banner">
				</div>
				<div class="banner-text">
					<p>REFILLABLE EDITION</p>
					<p>TOP-FILL OPEN POD VAPING SYSTEM</p>
					<p>GREAT FOR USE WITH NICOTINE</p>
					<p>SALT EJUICE, THC & CBD</p>
				</div>
			</li>
			<li class="pro-banner-r">
				<img src="/media/wysiwyg/product/re_banner_pro.png" alt="vladdin pod system vape kit">
			</li>
		</ul>
	</div>

	<div class="flavors-col ">
		<div class="flavors-main w-1200">
			<div class="introduce-title">
				<h2>FLAVORS REFILLED IN YOUR POD</h2>
				<h4></h4>
			</div>
			<div class="flavors-content">
				<img src="<?php echo $block->getViewFileUrl('images/home/flavors-s.gif') ?>" alt="pod system device construction">
				<div class="introduce-word">
					<ul class="clearfix">
						<li>
							<div class="introduce-img">
								<img src="<?php echo $block->getViewFileUrl('images/home/flavors-01.png') ?>" alt="operate icon">
							</div>
							<p>EASY TO USE TOP-FILL OPEN POD</p>
						</li>
						<li>
							<div class="introduce-img">
								<img src="<?php echo $block->getViewFileUrl('images/home/flavors-02.png') ?>" alt="delivers flavor icon" >
							</div>
							<p>PATENTED CERAMIC COIL INSIDE</p>
						</li>
						<li>
							<div class="introduce-img">
								<img src="<?php echo $block->getViewFileUrl('images/home/flavors-03.png') ?>" alt="patented icon" >
							</div>
							<p>DELIVERS PURE FLAVOR</p>
						</li>

					</ul>
				</div>
			</div>


		</div>
	</div>

	<div class="design-col">
		<div class="introduce-title">
			<h2>EASY-TO-USE TOP-FILL DESIGN</h2>
		</div>
		<img src="/media/wysiwyg/product/re_design_bg.jpg" alt="" style="vertical-align: top">
	</div>

	<div class="power-col">
		<div class="power-content w-1200">
			<div class="introduce-title">
				<h2>CONSISTENT AND EFFICIENT POWER DELIVERY </h2>
				<h4></h4>
			</div>

			<div class="power-info introduce-word">
				<ul class="clearfix">
					<li>
						<div class="introduce-img">
							<img src="<?php echo $block->getViewFileUrl('images/home/350.png') ?>" alt="battery icon"
								 class="wow rotateIn ">
						</div>
						<p>350mAh battery capacity</p>
					</li>
					<li>
						<div class="introduce-img">
							<img src="<?php echo $block->getViewFileUrl('images/home/usb.png') ?>" alt="USB icon" class="wow rotateIn"
								 data-wow-delay="0.1s">
						</div>
						<p>Universal Mirco-USB Port</p>
					</li>
					<li>
						<div class="introduce-img">
							<img src="<?php echo $block->getViewFileUrl('images/home/shuort.png') ?>" alt="protection icon"
								 class="wow rotateIn" data-wow-delay="0.2s">
						</div>
						<p>Short Circuit and Low Voltage Protection</p>
					</li>
					<li>
						<div class="introduce-img">
							<img src="<?php echo $block->getViewFileUrl('images/home/cixing.png') ?>" alt="connection icon"
								 class="wow rotateIn" data-wow-delay="0.3s">
						</div>
						<p>Magnetic connection </p>
					</li>
				</ul>
			</div>
		</div>
	</div>


	<div class="buy-col imgCenterPosition">
		<a href="/products" target="_blank" title="Buy Now">BUY NOW</a>
		<img src="/media/wysiwyg/product/re_by_bg.jpg" alt="" style="vertical-align: top">
	</div>
</div>