<p><b>Following shipping methods are available on our vladdin:</b></p>
<br />
<p><b>1. HK DHL EXPRESS:</b></p>
<p>Handle Time: Ship out from Shenzhen Warehouse in 24 hours in business day.</p>
<p>Delivery Time: 4-6 business days to most countries. When in peak season, there could be a 3-5 days delay.</p>
<p>Tracking number available in: 48 hours in business day.</p>
<p>Tracking Website:  <a href="http://www.dhl.com/en.html" title="dhl" target="_blank">http://www.dhl.com/en.html</a></p>
<p>Limitation:</p>
<ul>
    <li>Impossible to ship to PO BOX.</li>
    <li>Impossible to ship e-liquid & lithium battery cell like 18650.</li>
    <li>There is 0.5% chance that it will be inspected by China Customs, and the order will be delayed for 4-5 days.</li>
    <li>Vladdinvapor only charge shipping fee, the possible tax/duty is not included. Please kindly note that the Tax / Customs fee in destination country are at customer's expense.</li>
</ul>
<p><b>2. Air Post Parcel:</b></p>
<p>Available for most countries.</p>
<p>Handle Time: Ship out from Shenzhen Warehouse in 24 hours in business day.</p>
<p>Delivery Time: 15-40 business days to most countries. When in peak season, there could be a 3-5 days delay.</p>
<p>Tracking number available in: 48 hours in business day, can track order whthin one week after the tracking number is available.</p>
<p>Tracking website: <a href="https://www.17track.net/en" title="17track.net" target="_blank">https://www.17track.net/en</a></p>
<p>Maximum limit of each package is 2 KGS</p>
<br />

<p>Any Queation Feel Free to email <a href="mailto:support@vladdinvapor.com">support@vladdinvapor.com</a></p>
<p>------- Vladdin Service Team</p>
