<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="authorization-link">
	<?php if($customerSession->isLoggedIn()): ?>
		<a href="<?php echo $baseUrl; ?>customer/account/logout/">
            <?php echo $block->escapeHtml($block->getLabel()); ?>
		</a>
	<?php else: ?>
		<a href="javascript:;" onclick="_gaq.push(['_trackEvent','home_sign_in_button_01','Click','home_sign_in_button_01'])" >

            <?php echo $block->escapeHtml($block->getLabel()); ?>
			<script>
				require(['jquery'],
					function($) {
						$('.authorization-link a').click(function(){
							$(".modal-popup").css("visibility","visible");
							$(".modal-inner-wrap").css("transform","translateY(0%)");
						});
						
						$(document).on('click', '.action-close', function() {
							$(".modal-popup").css("visibility","hidden");
							$(".modal-inner-wrap").css("transform","translateY(200%)");
						});
					}
				);
			</script>
		</a>
	<?php endif; ?>
</li>

