<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php
$orderAdminDate = $block->formatDate(
    $block->getOrderAdminDate($_order->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);
$orderStoreDate = $block->formatDate(
    $_order->getCreatedAt(),
    \IntlDateFormatter::MEDIUM,
    true,
    $block->getTimezoneForStore($_order->getStore())
);
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Order & Account Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */?>
            <?php if ($_order->getEmailSent()):
                $_email = __('The order confirmation email was sent');
            else:
                $_email = __('The order confirmation email is not sent');
            endif; ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php if ($block->getNoUseOrderLink()): ?>
                        <?php /* @escapeNotVerified */ echo __('Order # %1', $_order->getRealOrderId()) ?> (<span><?php /* @escapeNotVerified */ echo $_email ?></span>)
                    <?php else: ?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order->getId()) ?>"><?php /* @escapeNotVerified */ echo __('Order # %1', $_order->getRealOrderId()) ?></a>
                        <span>(<?php /* @escapeNotVerified */ echo $_email ?>)</span>
                    <?php endif; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                <tr>
                    <th><?php /* @escapeNotVerified */ echo __('Order Date') ?></th>
                    <td><?php /* @escapeNotVerified */ echo $orderAdminDate ?></td>
                </tr>
                <?php if ($orderAdminDate != $orderStoreDate):?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __(
                                'Order Date (%1)',
                                $block->getTimezoneForStore($_order->getStore())
                            ) ?></th>
                        <td><?php /* @escapeNotVerified */ echo $orderStoreDate ?></td>
                    </tr>
                <?php endif;?>
                <tr>
                    <th><?php /* @escapeNotVerified */ echo __('Order Status') ?></th>
                    <td><span id="order_status"><?php /* @escapeNotVerified */ echo $_order->getStatusLabel() ?></span></td>
                </tr>
                <?php echo $block->getChildHtml(); ?>
                <?php if ($block->isSingleStoreMode() == false):?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Purchased From') ?></th>
                        <td><?php /* @escapeNotVerified */ echo $block->getOrderStoreName() ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRelationChildId()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Link to the New Order') ?></th>
                        <td><a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order->getRelationChildId()) ?>">
                                <?php /* @escapeNotVerified */ echo $_order->getRelationChildRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRelationParentId()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Link to the Previous Order') ?></th>
                        <td><a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order->getRelationParentId()) ?>">
                                <?php /* @escapeNotVerified */ echo $_order->getRelationParentRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRemoteIp() && $block->shouldDisplayCustomerIp()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Placed from IP') ?></th>
                        <td><?php /* @escapeNotVerified */ echo $_order->getRemoteIp(); echo($_order->getXForwardedFor()) ? ' (' . $block->escapeHtml($_order->getXForwardedFor()) . ')' : ''; ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('%1 / %2 rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></th>
                        <td><?php /* @escapeNotVerified */ echo $_order->getBaseToGlobalRate() ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('%1 / %2 rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></th>
                        <th><?php /* @escapeNotVerified */ echo $_order->getBaseToOrderRate() ?></th>
                    </tr>
                <?php endif; ?>
            </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /* Account Information */?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Account Information') ?></span>
                <div class="actions"><?php /* @escapeNotVerified */ echo $block->getAccountEditLink()?></div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Customer Name') ?></th>
                        <td>
                            <?php if ($_customerUrl = $block->getCustomerViewUrl()) : ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_customerUrl ?>" target="_blank">
                                    <span><?php echo $block->escapeHtml($_order->getCustomerName()) ?></span>
                                </a>
                            <?php else: ?>
                                <?php echo $block->escapeHtml($_order->getCustomerName()) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Email') ?></th>
                        <td><a href="mailto:<?php echo $block->escapeHtml($_order->getCustomerEmail()) ?>"><?php echo $block->escapeHtml($_order->getCustomerEmail()) ?></a></td>
                    </tr>
                    <?php if ($_groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo __('Customer Group') ?></th>
                            <td><?php /* @escapeNotVerified */ echo $_groupName ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data):?>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo $data['label'] ?></th>
                            <td><?php /* @escapeNotVerified */ echo $data['value'] ?></td>
                        </tr>
                    <?php endforeach;?>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Address Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-billing-address">
            <?php /* Billing Address */?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Billing Address') ?></span>
                <div class="actions"><?php /* @escapeNotVerified */ echo $block->getAddressEditLink($_order->getBillingAddress()); ?></div>
            </div>
            <address class="admin__page-section-item-content"><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getBillingAddress()); ?></address>
        </div>
        <?php if (!$block->getOrder()->getIsVirtual()): ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span>
                    <div class="actions"><?php /* @escapeNotVerified */ echo $block->getAddressEditLink($_order->getShippingAddress()); ?></div>
                </div>
                <address class="admin__page-section-item-content"><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getShippingAddress()); ?></address>
            </div>
        <?php endif; ?>
    </div>
</section>

<section class="admin__page-section ave40-erp">
	<div class="admin__page-section-title">
		<span class="title"><?php /* @escapeNotVerified */ echo __('Ave40-Erp 订单同步信息') ?></span>
		<button class="scalable" id="ave40_query_status_button">刷新状态</button>
	</div>
	<div class="admin__page-section-content">
		<div class="admin__page-section-item order_sync_info">
			<div id="ave40_order_status_text" style="display: none;"></div>
			<div id="ave40_order_status_loading">
				<span style="vertical-align: middle;">查询中 </span>
				<svg width="15" height="15" style="position:relative;vertical-align: middle;top:-1px;" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#ed6502">
					<g fill="none" fill-rule="evenodd">
						<g transform="translate(1 1)" stroke-width="2">
							<circle stroke-opacity=".5" cx="18" cy="18" r="18"></circle>
							<path d="M36 18c0-9.94-8.06-18-18-18">
								<animateTransform
										attributeName="transform"
										type="rotate"
										from="0 18 18"
										to="360 18 18"
										dur=".6s"
										repeatCount="indefinite"></animateTransform>
							</path>
						</g>
					</g>
				</svg>
			</div>
		</div>
		<div class="admin__page-section-item actual-arrival-amount">
            <?php /* Shipping Address */ ?>
			<div class="admin__page-section-item-title">
				<span class="title"><?php echo __('实际到账金额:') ?></span>
				<input type="text" id="ave40_erp_order_amount" readonly="readonly" style="opacity:0.5;"
					   old-value="<?php echo $this->getActualAmount(); ?>"
					   value="<?php echo $this->getActualAmount(); ?>"/>
				<button type="button" class='scalable' style="display:none;" id="ave40_erp_order_amount_edit">编辑</button>
				<button type="button" class='scalable' style="display:none;" id="ave40_erp_order_amount_save">保存</button>
				<button type="button" class='scalable' style="display:none;" id="ave40_erp_order_amount_cancel">取消</button>
			</div>
			<br>
<!--			富汇通的订单将按照公式计算,-->
			<i>订单实际到账金额在同步前才能修改, 同步中或者同步后都无法修改<br>0表示使用默认的金额, paypal支付的订单将直接查询实际到账, 其他订单显示订单的原价</i>
		</div>
		<br>
		<div>快递方式 :<?php echo $_order->getLogisticsProvider() ? $_order->getLogisticsProvider() : '暂无' ?></div>
		<div>快递单号 :<?php echo $_order->getExpressNo() ? $_order->getExpressNo() : '暂无' ?></div>
	</div>
	<script>
		require(['prototype'],function () {
			~function() {
				var ave40_order_status_text = document.getElementById('ave40_order_status_text');
				var ave40_order_status_loading = document.getElementById('ave40_order_status_loading');
				var ave40_query_status_button = document.getElementById('ave40_query_status_button');
				var ave40_erp_order_amount = document.getElementById('ave40_erp_order_amount');
				var ave40_erp_order_amount_edit = document.getElementById('ave40_erp_order_amount_edit');
				var ave40_erp_order_amount_save = document.getElementById('ave40_erp_order_amount_save');
				var ave40_erp_order_amount_cancel = document.getElementById('ave40_erp_order_amount_cancel');
				
				//查询同步状态
				~function () {
					ave40_query_status_button.onclick = function () {
						this.setAttribute('disabled', 'disabled');
						ave40_order_status_loading.style.display = 'block';
						ave40_order_status_text.style.display = 'none';
						ave40_erp_order_amount_cancel.click();
						
						setTimeout(function() {
							new Ajax.Request('<?php echo $this->getQueryStateUrl(); ?>', {
								parameters: {orderId: '<?php echo $_order->getId() ?>'},
								onSuccess: function(transport) {
									ave40_query_status_button.removeAttribute('disabled');
									var result = transport.responseJSON;
									
									if(!result) {
										ave40_order_status_text.innerHTML = '<span style="color:red;">查询失败</span>';
									} else {
										if(result.fail) {
											ave40_order_status_text.innerHTML = '<span style="color:red;">查询失败, '+result.message+'</span>';
										} else {
											ave40_order_status_text.innerHTML = result.data.html;
										}
									}
									
									//显示查询结果
									ave40_order_status_text.style.display = 'block';
									ave40_order_status_loading.style.display = 'none';
									
									if(!result.data.syncdata) {
										result.data.syncdata = {status: '<?php echo \Ave40\Base\Model\Mdw\Records::STATUS_PENDING ?>'};
									}
									
									//判断是否允许修改实际到账金额
									if(result.data.syncdata.status == '<?php echo \Ave40\Base\Model\Mdw\Records::STATUS_PENDING ?>'
										|| result.data.syncdata.status == '<?php echo \Ave40\Base\Model\Mdw\Records::STATUS_FAILURE ?>') {
										ave40_erp_order_amount_edit.style.display = '';
									} else {
										ave40_erp_order_amount_edit.style.display = 'none';
										
										if(result.data.syncdata.status == '<?php echo \Ave40\Base\Model\Mdw\Records::STATUS_COMPLETED ?>') {
											ave40_query_status_button.style.display = 'none';
										}
									}
								},
								
								onFailure: function () {
									ave40_query_status_button.removeAttribute('disabled');
									ave40_order_status_text.innerHTML = '<span style="color:red;">查询失败</span>';
								}
							});
						}, 50);
					};
				}();
				
				
				//立即查询
				ave40_query_status_button.click();
				
				//实际到账金额
				~function () {
					ave40_erp_order_amount_edit.onclick = function () {
						ave40_erp_order_amount.removeAttribute('readonly');
						ave40_erp_order_amount_edit.style.display = "none";
						ave40_erp_order_amount_save.style.display = "inline-block";
						ave40_erp_order_amount_cancel.style.display = "inline-block";
						ave40_erp_order_amount.focus();
						ave40_erp_order_amount.style.opacity=1;
					};
					
					ave40_erp_order_amount_cancel.onclick = function () {
						ave40_erp_order_amount.value = ave40_erp_order_amount.getAttribute('old-value');
						ave40_erp_order_amount.setAttribute('readonly', 'readonly');
						ave40_erp_order_amount_edit.style.display = "inline-block";
						ave40_erp_order_amount_save.style.display = "none";
						ave40_erp_order_amount_cancel.style.display = "none";
						ave40_erp_order_amount.style.opacity=0.5;
					};
					
					ave40_erp_order_amount_save.onclick = function () {
						var val = parseFloat(ave40_erp_order_amount.value);
						
						if(ave40_erp_order_amount.value.length == 0) {
							alert('请输入实际到账金额');
							ave40_erp_order_amount.focus();
							return ;
						}
						
						if(isNaN(val)) {
							alert('实际金额有误, 必须是数字');
							ave40_erp_order_amount.select();
							return ;
						}
						
						new Ajax.Request('<?php echo $this->getSaveActualAmountUrl(); ?>', {
							parameters: {amount:val, orderId: '<?php echo $_order->getId() ?>'},
							onSuccess: function(transport) {
								var result = transport.responseJSON;
								
								if(result.success) {
									ave40_erp_order_amount.value = result.data.amount;
									ave40_erp_order_amount.setAttribute('old-value', result.data.amount);
									ave40_erp_order_amount_cancel.click();
								} else {
									alert(result.message);
								}
							},
							
							onFailure: function () {
								alert('保存失败');
							}
						});
					};
				}();
			}();
		});
		
	</script>
</section>
