<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="block related ">
        <div class="block-title title">
            <strong id="block-relatedposts-heading" role="heading" aria-level="2">
                <?php echo __('Read More') ?>
            </strong>
        </div>
        <ol class="block-content clearfix">
            <?php foreach ($_postCollection as $_post) { ?>
                <li class="item">
                    <a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <div class="related-post-image" style="width: 374px;height: 210px">
                            <img src="<?php echo $_post->getFeaturedImage() ?>" alt="" >
                        </div>
                        <p class="related-post-title"><?php echo $block->escapeHtml($_post->getTitle()); ?></p>
                    </a>
                    <p class="related-post-date"><?php echo $_post->getPublishDate('F d, Y') ?></p>
                    <p class="related-post-text"><?php echo strip_tags($_post->getContent()) ?></p>
                </li>
            <?php } ?>
        </ol>
    </div>
    <?php } ?>
<?php } ?>