<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success 11111">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
	
	<?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $billingAddress = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($block->getOrderId())->getBillingAddress();
	?>
	
	<?php if(!isset($billingAddress['telephone']) || empty($billingAddress['telephone'])): ?>
	<div class="telphoneSaveWrapper" style="position:relative;">
		<h3>Add your phone number</h3>
		<input style="width: 200px;height: 36px;" id="telephone" type="text" name="telephone" / >
		<input id="orderIncrementId" type="hidden" value="<?php echo $block->escapeHtml($block->getOrderId()); ?>" name="orderIncrementId" / >
		<button style="background-color: #07a0ec;border-color: #07a0ec;color: #fff;position: relative;top: -2px;" class="telphonesave">save</button>
		<div class="description" style="margin-top: 10px;">Please offer your phone number so that we can contact you.</div>
		<div class="errormessage" style="display:none; width: 320px;padding: 10px;background-color: rgb(237, 237, 237);font-weight: bold;position: absolute;color: red;top: 10px;left: 20%;opacity: 0.9;"></div>
		<div class="successmessage" style="width: 320px; padding: 10px; background-color: rgb(219, 246, 213); font-weight: bold; position: absolute; top: 20px; left: 20%; display: none; opacity: 0.9;"></div>
	</div>
	<?php endif; ?>
</div>
<style>
	#registration {
		display: none;
	}
</style>
<?php
// 获取formkey
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey')->getFormKey();
?>

<script>
	require(['jquery'], function ($,ave40) {
		~function ($) {
			$('.telphonesave').click(function(){
				var _orderIncrementId =  $('.telphoneSaveWrapper #orderIncrementId').val();
				var _telephone = $('.telphoneSaveWrapper #telephone').val();
				var url = "<?php echo $this->getUrl('base/checkout/deal/');?>";
				$.ajax({
					type: 'POST',
					url: url,
					data: {orderIncrementId:_orderIncrementId,telephone:_telephone,form_key:'<?php echo $FormKey;?>'},
					beforeSend:function() {
						$('.telphoneSaveWrapper').append("<img style='position: absolute;top: 20px;left: 25%;width: 30px;' class='imageloading' src='<?php echo $block->getViewFileUrl("images/loader-1.gif") ?>'  />");
					},
					success: function(data) {
						$(".telphoneSaveWrapper .imageloading").remove();
						if(data.status_code == 1) {
							$('.successmessage').html(data.message);
							$('.successmessage').show(300);
							setInterval(function(){
								$('.successmessage').hide(300);
								$('.telphoneSaveWrapper').hide(300);
							},3000);
							
						}
						else {
							$(".telphoneSaveWrapper .imageloading").remove();
							$('.errormessage').html(data.message);
							$('.errormessage').show(300);
							setInterval(function(){
								$('.errormessage').hide(300);
							},3000);
						}
					},
					error:function(data) {
					
					},
					dataType: 'json'
				});
			});
		}(jQuery);
	});
</script>

