<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper quickcart-wrapper">
    <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart block-quickcart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'
        >
            <div id="minicart-content-wrapper" class="quickcart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
    
    <?php $_helper = $this->helper('WeltPixel\QuickCart\Helper\Data'); ?>
    <?php $storeId = $_helper->getStoreId(); ?>
    <style>
        .block-content-quickcart .quickcart-top {
            background: <?php echo $_helper->getHeaderBackground($storeId) ?>;
            color: <?php echo $_helper->getHeaderTextColor($storeId) ?>;
            height: <?php echo $_helper->getHeaderHeight($storeId) ?>;
            line-height: <?php echo $_helper->getHeaderHeight($storeId) ?>;
        }
        .block-content-quickcart .quickcart-top button.close {
            height: <?php echo $_helper->getHeaderBackground($storeId) ?>;
        }
        .block-content-quickcart .quickcart-top button.close span {
            color: <?php echo $_helper->getHeaderTextColor($storeId) ?>;
        }
        .block-content-quickcart .quickcart-top .action.close::before {
            color: <?php echo $_helper->getHeaderTextColor($storeId) ?>;
        }
        .block-content-quickcart .quickcart-bottom-container .subtotal {
            background: <?php echo $_helper->getSubtotalBackground($storeId) ?>;
            color: <?php echo $_helper->getSubtotalTextColor($storeId) ?>;
        }
    </style>
</div>