<?php
$pagesize = $this->getData('pagesize');
$cids = $this->getData('cids');
$cids = explode(",",$cids);
$_productCollection = $block->getLoadedProductCollection();
$_productCollection->setPageSize($pagesize);

/** @var Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor $_productCollection */
$_productCollection->getSelect()->join(['ci' => 'catalog_category_product_index'], 'ci.product_id=e.entity_id AND ci.store_id=1 AND ci.visibility IN(2, 4) AND ci.category_id in ('.implode("','", $cids).') ');
// $_productCollection->addAttributeToSort('ci.position', 'ASC');
$_productCollection->getSelect()->order('ci.position ASC');
// $_productCollection->addCategoriesFilter(array('in' => $cids));
$_helper = $this->helper('Magento\Catalog\Helper\Output');

?>
<?php if (!$_productCollection->count()): ?>
	<div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<style>
		.product-oth-avaliable-tip {
			background-color: rgba(194,195,195,0.329);
			border-radius: 12px;
			padding: 4px 10px;
			font-size: 12px;
			color: #666;
		}
        .product-oth-avaliable-tip span {
            color: rgb(200,200,200);
            padding: 0 2px;
        }
		
		.product-item-details .product-item-name a {
			hyphens:none !important;
		}
	</style>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
   
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
	<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
		<ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
				<div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
					<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
					</a>
					<div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
						<strong class="product name product-item-name">
							<a class="product-item-link"
							   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
							</a>
						</strong>
						
						<?php if($_product->getData('show_4_pack')): ?>
							<span class="product-oth-avaliable-tip">2<span>|</span>4 Pack Available</span>
						<?php else: ?>
							<span>&nbsp;</span>
						<?php endif; ?>
						
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        <div class="inquire-btn-box">
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="Buy Now" class="product-inquire-btn ">Buy Now &gt; </a>
                        </div>


						<div class="product-item-inner">
							
                            <?php if ($showDescription):?>
								<div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
									   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
								</div>
                            <?php endif; ?>
						</div>
					</div>
				</div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
		</ol>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
		<script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<!-- 显示头部广告  -->
<script>
    require(['jquery'], function($){
        $(function () {
            showTopAd('/media/wysiwyg/product/top_ad.jpg');
        })
    })
</script>






